### ISSUE TITLE
Some head highlights are reversed on female bases

### ISSUE THREAD

**Issue by joewhite** [makrohn/Universal-LPC-spritesheet#12]
The body layers include a shiny patch on the bald head. In the base LPC assets, this shiny patch is always on the left (toward the light source), no matter which direction the character is facing. But in the female layers, some of the images have the highlight in the upper-right instead.

For example, in row 6 (the left-facing spear animation), the second image in the row has the highlight on the right. The other images in that row have it on the left. So the highlight will jump around during animation.

This affects all of the female human recolorings.

**Comment by makrohn** [comment]
This is probably my bad - I frequently did the right-facing (or left-facing) poses first, and then reversed them for the other direction, without paying attention to the highlights.

**Comment by makrohn** [comment]
Closed by #13
