### ISSUE TITLE
Slippers don't always line up, and are missing for some animations

### ISSUE THREAD

**Issue by joewhite** [makrohn/Universal-LPC-spritesheet#14]
The various "slippers" footwear layers (designed for the female base forms) don't always line up with the feet. For example:
- In the west- and east-facing walkcycle animations, there are several frames where the toe sticks out past the end of the slipper. The same thing doesn't happen in the south-facing walkcycle animation, so it's not that these are meant to be open-toed slippers.
- In the north-facing slash animation, the slippers don't even touch the bottoms of the feet.

There are no slippers at all for the "thrust" and "bow" animations.

**Comment by makrohn** [comment]
Closed by #16
