### ISSUE TITLE
Move "white shirt" layer underneath "leather armor"

### ISSUE THREAD

**Issue by joewhite** [makrohn/Universal-LPC-spritesheet#21]
The current spritesheet has "white shirt (m)" above the "leather armor" layer group. This means you can't layer the leather armor (and shoulders) on top of the white shirt.

These should be put back the way they were in wulax's original xcf, with the "white shirt" layer below "leather armor" in the "torso" layer group, so you can get effects like the top-left sprite in [wulax's preview image](http://opengameart.org/content/lpc-medieval-fantasy-character-sprites).

**Comment by makrohn** [comment]
Closed by 6c54e8f8f1f1622139cf6f6bf00b8a22a7f5711f
