### ISSUE TITLE
Females Need.

### ISSUE THREAD

**Issue by cdjensen94** [makrohn/Universal-LPC-spritesheet#5]
The Females need more Clothing types.

**Comment by makrohn** [comment]
Right now I'm just working on combining all the content from the LPC (and adapting armor to women).  If you'd like to generate some more clothing for the ladies, though, be my guest!  There are a lot of layers in the .xcf right now that are for women, even if they're not marked as (female) yet.

**Comment by cdjensen94** [comment]
Okay, well I'll see how good of a spriter I can be. I'll fork this if you don't mind.

**Comment by makrohn** [comment]
Fork away!  Just keep in mind that Git is definitely NOT the best tool for collaboratively editing .xcf files, so if you do create something you want to see merged into the Universal Sprite Sheet, I'd recommend posting it to OGA, as well as submitting each layer in a pull request as a png so they can be manually added to the master sprite sheet.

**Comment by makrohn** [comment]
Closing issue in favor of more specific suggestions, and because of Joe's contributions.
