### ISSUE TITLE
online link not working

### ISSUE THREAD

**Issue by RyanDansie** [makrohn/Universal-LPC-spritesheet#51]
The link to the online version doesn't seem to work any more.

**Comment by jrconway3** [comment]
Gaurav had to change the link a while back. The link was updated on both Gaurav's and my fork's of the Universal LPC Spritesheet, but the main one hasn't gotten updated yet.

Here's the current link: http://gaurav.munjal.us/Universal-LPC-Spritesheet-Character-Generator

**Comment by ashes999** [comment]
Seems to be working now.
