### ISSUE TITLE
Add Dark Body & Elven Ears Recolors by Nila

### ISSUE THREAD

**Issue by Gaurav0** [makrohn/Universal-LPC-spritesheet#52]
http://opengameart.org/content/lpc-dark-elves

**Comment by jrconway3** [comment]
Ah, sweet, I planned to do dark elf recolors later once I had the opportunity to do so. I'll see about adding those recolors up this weekend if no one else gets to doing it before then.

**Comment by jrconway3** [comment]
I've committed all these to my repo now, added the recolors for noses and big ears, and also added these additions to the Character Generator HTML file which I then put in a pull request for. I'm not sure about the hair shading, though, so that's the one thing I left out.

**Comment by makrohn** [comment]
I'll try and get all of this merged tonight.

**Comment by jrconway3** [comment]
Sorry I kinda got carried away... I've slowed down for now, anyway. Work and I've got another project I've been trying to get a demo out for. Plus the one I wanted to do LPC sprites on I decided I wanted to work on a few maps before I go back to working on character sprite updates.

**Comment by makrohn** [comment]
Closed by merging jrconway's work.
